name: List merged branches

on:
  pull_request:
    branches: 
      [main, master]
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: SpiritXStorm/github-workflows/.github/workflows/slack-merged-branch.yml@main
    secrets: inherit
    
  call-lighthouse-workflow:
    needs: call-workflow
    uses: SpiritXStorm/github-workflows/.github/workflows/slack-lighthouse.yml@main
    secrets: inherit
    with:
      urls: 'https://total-party-ltd-ta-balloon-market-store-1-sandbox.mybigcommerce.com,https://total-party-ltd-ta-balloon-market-store-1-sandbox.mybigcommerce.com/balloons,https://total-party-ltd-ta-balloon-market-store-1-sandbox.mybigcommerce.com/super-stuffer-easter-bunny-package-1/'

  
