name: List merged branches

on:
  pull_request:
    branches: 
      [main, master]
    types: [opened, reopened]

jobs:
  call-slack-message:
    uses: SpiritXStorm/github-workflows/.github/workflows/slack-message.yml@main
    secrets: inherit
    with:
      channelId: ${{ vars.SLACK_CHANNEL_ID }}
      message: "@here deploying LIVE"
      
  call-workflow:
    uses: SpiritXStorm/github-workflows/.github/workflows/slack-merged-branch.yml@main
    secrets: inherit
    with:
      channelId: ${{ vars.SLACK_CHANNEL_ID }}
    
  call-lighthouse-workflow:
    needs: call-workflow
    uses: SpiritXStorm/github-workflows/.github/workflows/slack-lighthouse.yml@main
    secrets: inherit
    with:
      urls: ${{ vars.LIGHTHOUSE_URLS }}
      
  call-slack-message-success:
    if: ${{ success() }}
    uses: SpiritXStorm/github-workflows/.github/workflows/slack-message.yml@main
    secrets: inherit
    with:
      channelId: ${{ vars.SLACK_CHANNEL_ID }}
      message: "@here Deploy finished successfully"
          
  call-slack-message-failure:
    if: ${{ failure() }}
    uses: SpiritXStorm/github-workflows/.github/workflows/slack-message.yml@main
    secrets: inherit
    with:
      channelId: ${{ vars.SLACK_CHANNEL_ID }}
      message: "@here deploy FAILED"

  
