name: List merged branches

on:
  pull_request:
    branches: 
      - main
    types: [opened, reopened]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
    - name: Checkout release / hotgix branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Run diff
      run: |
          diff <(git branch -r --merged origin/${{ github.base_ref }}) <(git branch -r --merged origin/${{ github.head_ref }}) | grep -v 'origin/${{ github.base_ref }}|origin/${{ github.head_ref }}' | grep ">" | sed 's/>   origin\///g'
