name: List merged branches

on:
  pull_request:
    branches: 
      - main
    types: [opened, reopened]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch

      - name: Run git diff
        run: |
          diff <(git branch -r --merged origin/${{ github.base_ref }}) <(git branch -r --merged origin/${{ github.head_ref }}) | grep -vE '${{ github.base_ref }}|${{ github.head_ref }}' | grep ">" | sed 's/>   origin\///g'
