name: List merged branches

on:
  pull_request:
    branches: 
      [main, master]
    types: [opened, reopened]

jobs:
  diff:
    runs-on: ubuntu-latest

    outputs:
      merged-branches: ${{ steps.git-diff.outputs.diff }}

    steps:    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch

      - name: Run git diff
        id: git-diff
        run: |
          diff=$(diff <(git branch -r --merged origin/${{ github.base_ref }}) <(git branch -r --merged origin/${{ github.head_ref }}) | grep -vE "origin/${{ github.base_ref }}|origin/${{ github.head_ref }}" | grep ">" | sed 's/>   origin\///g')
          echo "$diff"
          
      - name: Post to a Slack channel
        if: ${{ steps.git-diff.outputs.diff != '' }}
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Following branch(es) going to be merged to ${{ github.base_ref }}:\n${{ steps.diff.outputs.diff }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
