name: List merged branches

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    name: build
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
    - name: Checkout release / hotgix branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Run diff
      run: |
          git diff ${{ github.base_ref }} ${{ github.head_ref }}    